// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX--lFKTtr1Tlu1LeCM39IYwAtG5FJ2bw',
    appId: '1:443280514584:web:f97adcd4f52740953d6d6d',
    messagingSenderId: '443280514584',
    projectId: 'farmacio-dbd69',
    authDomain: 'farmacio-dbd69.firebaseapp.com',
    storageBucket: 'farmacio-dbd69.firebasestorage.app',
    measurementId: 'G-DCMQGET7M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXtCzxh8_xajxj10G9S3r--qm3PYQVfdM',
    appId: '1:443280514584:android:c502041a9e26894d3d6d6d',
    messagingSenderId: '443280514584',
    projectId: 'farmacio-dbd69',
    storageBucket: 'farmacio-dbd69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByBiL_82kTnlzznWT1xUc3mPDIDT9uV6I',
    appId: '1:443280514584:ios:d15f94c5d65ab7e43d6d6d',
    messagingSenderId: '443280514584',
    projectId: 'farmacio-dbd69',
    storageBucket: 'farmacio-dbd69.firebasestorage.app',
    iosBundleId: 'com.example.farmacioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByBiL_82kTnlzznWT1xUc3mPDIDT9uV6I',
    appId: '1:443280514584:ios:d15f94c5d65ab7e43d6d6d',
    messagingSenderId: '443280514584',
    projectId: 'farmacio-dbd69',
    storageBucket: 'farmacio-dbd69.firebasestorage.app',
    iosBundleId: 'com.example.farmacioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX--lFKTtr1Tlu1LeCM39IYwAtG5FJ2bw',
    appId: '1:443280514584:web:5cba37d52e1ade9e3d6d6d',
    messagingSenderId: '443280514584',
    projectId: 'farmacio-dbd69',
    authDomain: 'farmacio-dbd69.firebaseapp.com',
    storageBucket: 'farmacio-dbd69.firebasestorage.app',
    measurementId: 'G-BN22QL9VRP',
  );
}
